/**
 * Database Schema - Drizzle ORM
 *
 * Defines the database tables and their TypeScript types.
 */

import {
  pgTable,
  varchar,
  timestamp,
  boolean,
  integer,
  bigint,
  uuid,
  jsonb,
  index,
  pgEnum,
} from 'drizzle-orm/pg-core';

// ---------------------------------------------------------------------------
// Enums
// ---------------------------------------------------------------------------

/**
 * Service Order Type Enum
 *
 * Types: plan_subscription
 * Note: Can be extended with 'reserved_capacity', 'savings_plan', etc.
 */
export const serviceOrderTypeEnum = pgEnum('service_order_type', [
  'plan_subscription',
]);

/**
 * Service Order Status Enum
 *
 * Statuses: DRAFT, ACTIVE, PAST_DUE, BLOCKED, CANCELED, EXPIRED
 */
export const serviceOrderStatusEnum = pgEnum('service_order_status', [
  'DRAFT',
  'ACTIVE',
  'PAST_DUE',
  'BLOCKED',
  'CANCELED',
  'EXPIRED',
]);

// ---------------------------------------------------------------------------
// Service Orders Table
// ---------------------------------------------------------------------------

/**
 * Service Orders Table
 *
 * Main table for managing service subscriptions and orders.
 *
 */
export const serviceOrders = pgTable(
  'service_order',
  {
    // Primary Key - UUID generated by database
    serviceOrderId: uuid('service_order_id').primaryKey().defaultRandom(),

    // Account reference
    accountId: bigint('account_id', { mode: 'number' }).notNull(),

    // Service Order type and status
    type: serviceOrderTypeEnum('type').notNull(),
    status: serviceOrderStatusEnum('status').notNull(),

    // Plan reference (external reference to Product API)
    planId: uuid('plan_id').notNull(),

    // Gateway reference (optional, references gateway table)
    gatewayId: uuid('gateway_id'),

    // Validity period
    startDate: timestamp('start_date', { mode: 'date', withTimezone: true }),
    endDate: timestamp('end_date', { mode: 'date', withTimezone: true }),

    // Current billing period
    currentPeriodStart: timestamp('current_period_start', {
      mode: 'date',
      withTimezone: true,
    }),
    currentPeriodEnd: timestamp('current_period_end', {
      mode: 'date',
      withTimezone: true,
    }),

    // Auto-renewal flag
    autoRenew: boolean('auto_renew').default(true),

    // Auditing - Marco Civil da Internet (Brazil compliance)
    // Note: Using varchar for INET type as Drizzle doesn't have native INET support
    ip: varchar('ip', { length: 45 }).notNull(),
    port: integer('port').notNull(),
    ipFwd: varchar('ip_fwd', { length: 45 }),
    portFwd: integer('port_fwd'),
    timezone: varchar('timezone', { length: 50 }).notNull(),

    // Metadata - Fiscal/billing data in JSONB (tax_id, legal_name, billing_address, etc.)
    metadata: jsonb('metadata').default({}),

    // Timestamps
    createdAt: timestamp('created_at', {
      mode: 'date',
      withTimezone: true,
    })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp('updated_at', {
      mode: 'date',
      withTimezone: true,
    })
      .notNull()
      .defaultNow(),

    // Last editor tracking
    lastEditor: varchar('last_editor', { length: 100 }),
  },
  (table) => [
    // Index on account_id for fast lookups by account
    index('idx_service_order_account_id').on(table.accountId),
    // Index on status for filtering
    index('idx_service_order_status').on(table.status),
    // Index on type for filtering
    index('idx_service_order_type').on(table.type),
    // Index on dates for period queries
    index('idx_service_order_dates').on(table.startDate, table.endDate),
    // Index on plan_id for plan-related queries
    index('idx_service_order_plan_id').on(table.planId),
    // Index on gateway_id for gateway-related queries
    index('idx_service_order_gateway_id').on(table.gatewayId),
  ]
);

// ---------------------------------------------------------------------------
// Webhook Events Table
// ---------------------------------------------------------------------------

/**
 * Webhook Event Status Enum
 *
 * Statuses: pending, processing, processed, failed
 */
export const webhookEventStatusEnum = pgEnum('webhook_event_status', [
  'pending',
  'processing',
  'processed',
  'failed',
]);

/**
 * Webhook Events Table
 *
 * Stores incoming webhook events from Stripe for processing.
 * Provides idempotency and audit trail for all webhook events.
 */
export const webhookEvents = pgTable(
  'webhook_event',
  {
    // Primary Key - UUID generated by database
    id: uuid('id').primaryKey().defaultRandom(),

    // Stripe event ID (used for idempotency)
    stripeEventId: varchar('stripe_event_id', { length: 255 }).notNull().unique(),

    // Event type from Stripe (e.g., 'checkout.session.completed')
    eventType: varchar('event_type', { length: 100 }).notNull(),

    // Full event payload as JSONB
    payload: jsonb('payload').notNull(),

    // Processing status
    status: webhookEventStatusEnum('status').notNull().default('pending'),

    // Error message (if processing failed)
    errorMessage: varchar('error_message', { length: 500 }),

    // Processing timestamps
    processedAt: timestamp('processed_at', {
      mode: 'date',
      withTimezone: true,
    }),

    // Timestamps
    createdAt: timestamp('created_at', {
      mode: 'date',
      withTimezone: true,
    })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp('updated_at', {
      mode: 'date',
      withTimezone: true,
    })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    // Index on stripe_event_id for fast idempotency checks
    index('idx_webhook_event_stripe_id').on(table.stripeEventId),
    // Index on status for processing queue queries
    index('idx_webhook_event_status').on(table.status),
    // Index on event_type for filtering
    index('idx_webhook_event_type').on(table.eventType),
    // Index on created_at for ordering
    index('idx_webhook_event_created_at').on(table.createdAt),
  ]
);

// ---------------------------------------------------------------------------
// Test Users Table (for testing database connections)
// ---------------------------------------------------------------------------

/**
 * Test Users Table
 *
 * A simple table for testing the RDS Data API connection.
 */
export const testUsers = pgTable('test_users', {
  id: integer('id').primaryKey().generatedAlwaysAsIdentity(),
  name: varchar('name', { length: 100 }).notNull(),
  email: varchar('email', { length: 255 }).notNull(),
  active: boolean('active').default(true),
  createdAt: timestamp('created_at').defaultNow(),
});

// ---------------------------------------------------------------------------
// Type Exports
// ---------------------------------------------------------------------------

/**
 * Type for selecting a ServiceOrder (all fields)
 */
export type ServiceOrder = typeof serviceOrders.$inferSelect;

/**
 * Type for inserting a ServiceOrder (serviceOrderId and timestamps are optional)
 */
export type NewServiceOrder = typeof serviceOrders.$inferInsert;

/**
 * Type for selecting a TestUser (all fields)
 */
export type TestUser = typeof testUsers.$inferSelect;

/**
 * Type for inserting a TestUser (id and createdAt are optional)
 */
export type NewTestUser = typeof testUsers.$inferInsert;

/**
 * Type for selecting a WebhookEvent (all fields)
 */
export type WebhookEvent = typeof webhookEvents.$inferSelect;

/**
 * Type for inserting a WebhookEvent (id and timestamps are optional)
 */
export type NewWebhookEvent = typeof webhookEvents.$inferInsert;

// ---------------------------------------------------------------------------
// Plan Transition Table
// ---------------------------------------------------------------------------

/**
 * Plan Transition Type Enum
 *
 * Types: signup, upgrade, downgrade, cancel, reactivate
 */
export const planTransitionTypeEnum = pgEnum('plan_transition_type', [
  'signup',
  'upgrade',
  'downgrade',
  'cancel',
  'reactivate',
]);

/**
 * Plan Transition Status Enum
 *
 * Statuses: pending, completed, failed
 */
export const planTransitionStatusEnum = pgEnum('plan_transition_status', [
  'pending',
  'completed',
  'failed',
]);

/**
 * Plan Transitions Table
 *
 * Tracks all plan transitions for an account (signups, upgrades, downgrades, etc.)
 */
export const planTransitions = pgTable(
  'plan_transition',
  {
    // Primary Key - UUID generated by database
    id: uuid('id').primaryKey().defaultRandom(),

    // Service Order reference
    serviceOrderId: uuid('service_order_id').notNull(),

    // Account reference
    accountId: bigint('account_id', { mode: 'number' }).notNull(),

    // Transition type and status
    transitionType: planTransitionTypeEnum('transition_type').notNull(),
    status: planTransitionStatusEnum('status').notNull(),

    // Plan references (from_plan_id is null for signup)
    fromPlanId: uuid('from_plan_id'),
    toPlanId: uuid('to_plan_id').notNull(),

    // Effective immediately flag
    effectiveImmediately: boolean('effective_immediately').notNull().default(false),

    // Timestamps for transition lifecycle
    startedAt: timestamp('started_at', {
      mode: 'date',
      withTimezone: true,
    }).notNull(),
    completedAt: timestamp('completed_at', {
      mode: 'date',
      withTimezone: true,
    }),
    createdAt: timestamp('created_at', {
      mode: 'date',
      withTimezone: true,
    })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    // Index on service_order_id for fast lookups
    index('idx_plan_transition_service_order_id').on(table.serviceOrderId),
    // Index on account_id for fast lookups by account
    index('idx_plan_transition_account_id').on(table.accountId),
    // Index on status for filtering
    index('idx_plan_transition_status').on(table.status),
    // Index on transition_type for filtering
    index('idx_plan_transition_type').on(table.transitionType),
    // Index on to_plan_id for plan-related queries
    index('idx_plan_transition_to_plan_id').on(table.toPlanId),
  ]
);

// ---------------------------------------------------------------------------
// Type Exports
// ---------------------------------------------------------------------------

/**
 * Webhook Event Status values (for runtime validation)
 */
export type WebhookEventStatus =
  (typeof webhookEventStatusEnum.enumValues)[number];

/**
 * Service Order Type values (for runtime validation)
 */
export type ServiceOrderType = (typeof serviceOrderTypeEnum.enumValues)[number];

/**
 * Service Order Status values (for runtime validation)
 */
export type ServiceOrderStatus =
  (typeof serviceOrderStatusEnum.enumValues)[number];

/**
 * Type for selecting a PlanTransition (all fields)
 */
export type PlanTransition = typeof planTransitions.$inferSelect;

/**
 * Type for inserting a PlanTransition (id and timestamps are optional)
 */
export type NewPlanTransition = typeof planTransitions.$inferInsert;

/**
 * Plan Transition Type values (for runtime validation)
 */
export type PlanTransitionType = (typeof planTransitionTypeEnum.enumValues)[number];

/**
 * Plan Transition Status values (for runtime validation)
 */
export type PlanTransitionStatus = (typeof planTransitionStatusEnum.enumValues)[number];
